version: '3'
services:
  order:
    container_name: order
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: order
    ports:
        - "5432:5432"
    networks:
        - local

  payment:
    container_name: payment
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: payment
    ports:
        - "5433:5432"
    networks:
        - local

  inventory:
    container_name: inventory
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: inventory
    ports:
        - "5434:5432"
    networks:
        - local

  delivery:
    container_name: delivery
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: delivery
    ports:
        - "5435:5432"
    networks:
        - local

  zookeeper:
    container_name: zookeeper_test
    image: confluentinc/cp-zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - local

  kafka:
      container_name: kafka_test
      image: confluentinc/cp-kafka
      ports:
        - "29092:29092"
      environment:
        KAFKA_BROKER_ID: 1
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
        KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      restart: on-failure
      networks:
        - local

  order-service:
    container_name: order-service
    build:
      context: ./order
      dockerfile: Dockerfile
    depends_on:
      - order
    ports:
        - "8080:8080"
    restart: on-failure
    networks:
       - local

  inventory-service:
    container_name: inventory-service
    build:
      context: ./inventory
      dockerfile: Dockerfile
    depends_on:
      - inventory
    ports:
        - "8084:8084"
    restart: on-failure
    networks:
       - local

networks:
    local:
        driver: bridge

